name = "mt-naeun-wedding"
main = "functions/guestbook.ts"
compatibility_date = "2025-10-04"

[[d1_databases]]
binding = "my_wedding"
database_name = "my-wedding"
database_id = "b980f0d8-8b10-431d-b2d2-45b8d9a5cc08"
